import type { Metadata } from "next";
import "./globals.css";
import { TanstackProvider } from "@/components/providers/tanstack-provider";
import { ThemeProvider } from "@/components/theme-provider";
import {
  Inter,
  DM_Sans,
  Instrument_Serif,
  Playfair_Display,
} from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
  variable: "--font-Instrument", // Mencocokkan --font-Instrument di CSS kamu
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ["normal", "italic"],
  variable: "--font-display", // Mencocokkan --font-display di CSS kamu
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-body", // Ini mencocokkan variabel di CSS kamu
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${dmSans.variable} ${instrumentSerif.variable} ${playfairDisplay.variable}`}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackProvider>{children}</TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
